baseURL = "https://yourdomain.com/"
languageCode = "en-us"
title = "Rails Network FAQ"
theme = "hugo-book"

[params]
  author = "Liquid"
  description = "Rails Network FAQ"
  dateFormat = "January 2, 2024"
  # Add any other custom parameters specific to the Book theme

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      tableOfContents = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      taskList = true

[outputFormats]
  [outputFormats.RSS]
    baseName = "rss"
    mediaType = "application/rss+xml"
    isPlainText = true
    notAlternative = true

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  # Add more menu items as needed

[params.logo]
  # You can specify a logo for your site if needed
  src = "images/logo.png"
  alt = "Logo Alt Text"
  width = 100
  height = 100

# Customize further as needed for your specific content and preferences

